ALTER TABLE "Event" ADD COLUMN "coverImageUrl" TEXT;
ALTER TABLE "Event" ADD COLUMN "coverImageKey" TEXT;
ALTER TABLE "Event" ADD COLUMN "coverImageSource" TEXT;
ALTER TABLE "Event" ADD COLUMN "coverImagePositionX" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "Event" ADD COLUMN "coverImagePositionY" INTEGER NOT NULL DEFAULT 50;
